### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KamranABD-B27**

### CODE REVIEW

**Review by Salih099 — APPROVED** [review]
Look's Good 👍

**Comment by KamranABD-B27** [comment]
Can you guys review and merge the week2 package into master, Thx

**Comment by Salih099** [comment]
I did

**Comment by KamranABD-B27** [comment]
Thanks Salih!

**Review by MayilaPaerhati — APPROVED** [review]

**Review by MayilaPaerhati — CHANGES_REQUESTED** [review]
please only keep week2, thanks

**Pull request closed without merging**
